# Generated by Django 6.1 on 2026-08-15 16:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('label_type', models.CharField(choices=[('custom', 'Custom'), ('course', 'Course')], default='custom', max_length=20)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('done', 'Done'), ('archived', 'Archived')], default='ongoing', max_length=20)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('deadline_time', models.TimeField(blank=True, null=True)),
                ('notify_before_deadline', models.BooleanField(default=False)),
                ('color', models.CharField(default='#60a5fa', max_length=50)),
                ('icon_seed', models.IntegerField(default=0)),
                ('platform', models.CharField(choices=[('manual', 'Manual'), ('canvas', 'Canvas'), ('google_classroom', 'Google Classroom'), ('ustep', 'USTeP'), ('google_calendar', 'Google Calendar'), ('ocr', 'OCR')], default='manual', max_length=50)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('source_id', models.CharField(blank=True, default='', max_length=255)),
                ('original_link', models.URLField(blank=True, default='', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.user')),
            ],
            options={
                'db_table': 'atlas_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
