# Generated by Django 6.1 on 2026-08-15 16:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(blank=True, default='', max_length=50)),
                ('instructor_name', models.CharField(blank=True, default='', max_length=255)),
                ('room_location', models.CharField(blank=True, default='', max_length=255)),
                ('color', models.CharField(default='#3b82f6', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.user')),
            ],
            options={
                'db_table': 'atlas_courses',
                'ordering': ['-created_at'],
            },
        ),
    ]
