import { NextResponse, type NextRequest } from "next/server";

// In-memory token store (scoped per process, cleared on restart)
// Key: nonce (random ID generated by Electron), Value: { refresh_token, timestamp }
const pendingTokens = new Map<string, { refresh_token: string; timestamp: number }>();

export async function POST(request: NextRequest) {
  const body = await request.json();
  const { nonce, refresh_token } = body;

  if (!nonce || !refresh_token) {
    return NextResponse.json({ error: "missing_fields" }, { status: 400 });
  }

  // Store for 5 minutes
  pendingTokens.set(nonce, { refresh_token, timestamp: Date.now() });

  // Clean up old tokens
  for (const [key, val] of pendingTokens.entries()) {
    if (Date.now() - val.timestamp > 5 * 60 * 1000) {
      pendingTokens.delete(key);
    }
  }

  return NextResponse.json({ ok: true });
}

export async function GET(request: NextRequest) {
  const nonce = request.nextUrl.searchParams.get("nonce");
  if (!nonce) {
    return NextResponse.json({ error: "missing_nonce" }, { status: 400 });
  }

  const entry = pendingTokens.get(nonce);
  if (!entry) {
    return NextResponse.json({ ready: false });
  }

  // Return once and delete
  pendingTokens.delete(nonce);
  return NextResponse.json({ ready: true, refresh_token: entry.refresh_token });
}
